name: CI-Auto-Deploy  #deploy to AWS S3 from 7:55, 11.55, 15.55, 20.55 every 4 hours

on: 
    schedule:
    - cron: '55 2,15,19,23 * * *'
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2' 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm install react-scripts        
      env:
        CI: true  
    - name: Upload latest data file to S3 bucket ...
      run: | #aws s3 cp ./public/areas.json s3://covid-19-statistics/  
          npm run build
          npm run deploy  
