name: SEND-Heart-Beat

on: 
    schedule:
    - cron: '15 * * * *'
      
jobs:
  update:   
    runs-on: ubuntu-latest
    
    steps:
    - name: Send heart beat to heroku site ...
      run: curl https://covid-19-statistics.herokuapp.com/
