# This action is used to keep heroku site alive other than sleeping when idle

name: SEND-Heart-Beat 

on: 
    schedule:
    - cron: '*/20 * * * *'
      
jobs:
  update:   
    runs-on: ubuntu-latest
    
    steps:
    - name: Send heart beat to heroku site ...
      run: curl https://covid-19-statistics.herokuapp.com/
